#!/bin/bash -ex

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

echo Setting up Python virtual environment
mkdir -p build
python3 -m venv build/venv
. build/venv/bin/activate

echo $PATH
#update pip3
pip3 install --upgrade pip
echo Adding pyinstaller
#pip3 install pyinstaller
pip3 install https://github.com/rokm/pyinstaller/archive/macos11-arm-support.zip

echo Installing cbdep requirements
pip3 install -r ${SCRIPTPATH}/requirements.txt

echo Compiling cbdep
PYINSTDIR=$(pwd)/build/pyinstaller
mkdir -p ${PYINSTDIR}
pyinstaller --log-level DEBUG \
    --add-data ${SCRIPTPATH}/cbdep.config:. \
    --workpath ${PYINSTDIR} \
    --specpath ${PYINSTDIR} \
    --distpath dist --noconfirm \
    --onefile \
    --paths ${SCRIPTPATH}/cbdep/scripts \
    ${SCRIPTPATH}/cbdep/scripts/cbdep.py
